affiliations:
  - id: ucdphs-epi
    name: Division of Epidemiology, Department of Public Health Sciences, School of Medicine, University of California, Davis, CA, United States
    department: Division of Epidemiology, Department of Public Health Sciences
    city: Davis
    state: CA
    country: United States
  - id: ucdphs-biostats
    name: Division of Biostatistics, Department of Public Health Sciences, School of Medicine, University of California, Davis, CA, United States
    department: Division of Biostatistics, Department of Public Health Sciences
    city: Davis
    state: CA
    country: United States

project:
  type: book
  output-dir: docs

book:
  title: "UCD-SeRG Lab Manual"
  author:
    - name: Kristen Aiemjoy
      affiliations:
        - ref: ucdphs-epi
      email: kaiemjoy@health.ucdavis.edu

    - name: Ezra Morrison
      affiliations:
        - ref: ucdphs-biostats
      email: demorrison@ucdavis.edu
  date: last-modified
  date-format: "[Last updated:] YYYY-MM-DD"
  repo-url: https://github.com/UCD-SERG/lab-manual
  repo-actions: [edit, source, issue]
  downloads: [pdf, epub, docx]
  chapters:
    - index.qmd
    - 01-culture-and-conduct.qmd
    - 02-communication.qmd
    - 03-reproducibility.qmd
    - 04-code-repositories.qmd
    - 05-coding-practices.qmd
    - 06-coding-style.qmd
    - 06a-r-guidelines.qmd
    - 07-big-data.qmd
    - 08-data-masking.qmd
    - 09-github.qmd
    - 10-unix.qmd
    - 11-reproducible-environments.qmd
    - 12-code-publication.qmd
    - 13-data-publication.qmd
    - 14-slurm.qmd
    - 15-checklists.qmd
    - 16-resources.qmd
  page-navigation: true

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    number-sections: true
    embed-resources: false
  pdf:
    geometry:
      - top=15mm
      - bottom=20mm
    keep-md: false
    keep-tex: false
    toc: true
    fig-pos: "H"
    hyperrefoptions:
    - bookmarksnumbered=true
    toc-title: Contents
    df-print: tibble
    links-as-notes: true
    documentclass: scrbook
    classoption: [twoside=off]
    shift-heading-level-by: 0
    toc-depth: 2
    number-sections: true
    number-depth: 3
    colorlinks: true
  docx:
    toc: true
    number-sections: true
    highlight-style: github
  epub:
    toc: true
    number-sections: true

editor: source
